export {MantencionKrono as MantencionKrono, MantencionFloobest as MantencionFloobest, MantencionBoen as MantencionBoen};

const MantencionKrono: string[] = [
"BN1516PROSIL1",
"BN1535PROSIL1",
"BN5936PROSIL1",
"BN8631PROSIL1",
"BN8633PROSIL1",
"BNK268PROSIL1",
"BNK337PROSIL1",
"BNK406PROSIL1",
"BNK415PROSIL1"
];

const MantencionBoen: string[] = [
    "E2GD43FD",
    "EBG8V5FD",
    "EBG8V5JD",
    "EBG8VKFD",
    "EBG8VKJD",
    "EBGD43FD",
    "EBGD43JD",
    "EBGDV3FD",
    "EBGDV3JD",
    "EBGDVKFD",
    "EBGDVKJD",
    "EBGV33FD",
    "EBGV43FD",
    "EIP2356D",
    "ELG835FD",
    "EYG8VPPD/VIVO",
    "GBGDZKFD",
    "OHG8VKFD",
    "OHG8VKJD",
    "OHGDVKFD",
    "OZH8VKFD",
    "PEG843FD",
    "PFGV43FD",
    "PHGD43FD",
    "SLGVZKWD",
    "SNGVZKWD",
    "XHH8VMFD",
    "XYGV4KFD",
    "XZG8VKFD",
    "XZGVVKFD",
    "YCGVVKFD"
];

const MantencionFloobest: string[] = [
    "CHEVRON DE/5/5/I/4VA.",
    "CHEVRON DE/5/5/I/4VB.",
    "CHEVRON FU/5/5/I/4VA.",
    "CHEVRON FU/5/5/I/4VB.",
    "CHEVRON UR/5/5/I/4VA.",
    "CHEVRON UR/5/5/I/4VB.",
    "CONCRETE BL/5/5/E/4V.",
    "CONCRETE GR/5/5/E/4V.",
    "CONCRETE GREY/5/5/E/4V.",
    "CONCRETE WH/5/5/E/4V.",
    "FOREST CI/5/5/I/4V.",
    "FOREST CL/5/5/I/4V.",
    "FOREST DE/5/5/I/4V.",
    "FOREST GR/5/5/I/4V.",
    "FOREST GRAY/5/5/I/4V.",
    "FOREST MA/4/3/E/4V.",
    "FOREST NE/5/5/I/4V.",
    "FOREST NO/5/5/I/4V.",
    "FOREST OA/5/5/I/4V.",
    "FOREST SA/4/3/E/4V.",
    "FOREST TA/5/5/I/4V.",
    "FOREST UR/5/5/I/4V.",
    "FOREST WA/5/5/I/4V.",
    "LEGNO AS/5/5/I/4V.",
    "LEGNO BR/5/5/I/4V."
];